In [25]:
import numpy as np
import random
import eng_to_ipa as ipa

In [71]:
text = "If I should stay I would only be in your way So I'll go but I know I'll think of you every step of the way And I... will always love you, ooh Will always love you You My darling, you... Mmm-mm Bittersweet memories – That is all I'm taking with me So good-bye Please don't cry: We both know I'm not what you, you need And I... will always love you I... will always love you You, ooh [Instrumental / Sax solo] I hope life treats you kind And I hope you have all you've dreamed of And I wish you joy and happiness But above all this I wish you love And I... will always love you I will always love you I will always love you I will always love you I will always love you I, I will always love you You Darling, I love you I'll always... I'll always love you Ooh Ooh "

In [72]:
#text = open("hp.txt", "r").read()


In [73]:
text = ipa.convert(text)

In [74]:
print(text)

ɪf aɪ ʃʊd steɪ aɪ wʊd ˈoʊnli bi ɪn jʊr weɪ soʊ aɪl goʊ bət aɪ noʊ aɪl θɪŋk əv ju ˈɛvəri stɛp əv ðə weɪ ənd aɪ... wɪl ˈɔlˌweɪz ləv ju, u wɪl ˈɔlˌweɪz ləv ju ju maɪ ˈdɑrlɪŋ, ju... mmm-mm* ˈbɪtərsˌwit ˈmɛməriz –* ðət ɪz ɔl əm ˈteɪkɪŋ wɪθ mi soʊ ˈgʊdˌbaɪ pliz doʊnt kraɪ: wi boʊθ noʊ əm nɑt wət ju, ju nid ənd aɪ... wɪl ˈɔlˌweɪz ləv ju aɪ... wɪl ˈɔlˌweɪz ləv ju ju, u [ˌɪnstrəˈmɛnəl  sæks ˈsoʊˌloʊ] aɪ hoʊp laɪf trits ju kaɪnd ənd aɪ hoʊp ju hæv ɔl juv drimd əv ənd aɪ wɪʃ ju ʤɔɪ ənd ˈhæpinəs bət əˈbəv ɔl ðɪs aɪ wɪʃ ju ləv ənd aɪ... wɪl ˈɔlˌweɪz ləv ju aɪ wɪl ˈɔlˌweɪz ləv ju aɪ wɪl ˈɔlˌweɪz ləv ju aɪ wɪl ˈɔlˌweɪz ləv ju aɪ wɪl ˈɔlˌweɪz ləv ju aɪ, aɪ wɪl ˈɔlˌweɪz ləv ju ju ˈdɑrlɪŋ, aɪ ləv ju aɪl ˈɔlˌweɪz... aɪl ˈɔlˌweɪz ləv ju u u


In [75]:
l = len(text)
mat = np.zeros((7000,7000))

In [76]:
seen = {}

In [77]:
#toDo: change seen into a dictionary
seen[text[0]] = 0
count = 0
prev = 0
for i in range(1,len(text)):
    if text[i] not in seen:
        count+=1
        seen[text[i]] = count
    t = seen[text[i]]
    mat[t][prev] += 1
    prev = t

In [78]:
#delete data of 1 or 0
mat= np.delete(mat,np.where(~mat.any(axis=1))[0], axis=0)
mat= np.delete(mat,np.where(~mat.any(axis=0))[0], axis=1)

In [79]:
print(mat)

[[ 0.  0.  2. ...  0.  0.  0.]
 [ 2.  0.  0. ...  0.  0.  0.]
 [19.  2.  1. ...  1.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  3. ...  0.  0.  0.]
 [ 0.  0.  1. ...  0.  0.  0.]]


In [80]:
sum_of_rows = mat.sum(axis=1)
normalized_array = mat / sum_of_rows[:, np.newaxis]

In [81]:
print(seen)
normalized_array

{'ɪ': 0, 'f': 1, ' ': 2, 'a': 3, 'ʃ': 4, 'ʊ': 5, 'd': 6, 's': 7, 't': 8, 'e': 9, 'w': 10, 'ˈ': 11, 'o': 12, 'n': 13, 'l': 14, 'i': 15, 'b': 16, 'j': 17, 'r': 18, 'g': 19, 'ə': 20, 'θ': 21, 'ŋ': 22, 'k': 23, 'v': 24, 'u': 25, 'ɛ': 26, 'p': 27, 'ð': 28, '.': 29, 'ɔ': 30, 'ˌ': 31, 'z': 32, ',': 33, 'm': 34, 'ɑ': 35, '-': 36, '*': 37, '–': 38, ':': 39, '[': 40, 'æ': 41, ']': 42, 'h': 43, 'ʤ': 44}


array([[0.        , 0.        , 0.03030303, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.12101911, 0.01273885, 0.00636943, ..., 0.00636943, 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.75      , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ]])

In [82]:
currRow = random.randint(0, normalized_array[0].size)
currRow

31

In [83]:
s = ""
key_list = list(seen.keys())
vals = list(seen.values())
for i in range(7000):
    n = random.randint(0, normalized_array[0].size)
    totalN = 0
    steps = 0
    randie = np.random.rand(1)[0]
    for p in normalized_array[currRow]:
        totalN += p
        if randie < totalN:
            s+= key_list[vals.index(steps)]
            currRow = steps
            break
        steps+=1
        
    

In [84]:
s[::-1]

'ənitəndˌweɪŋksoʊ hoʊp weɪ wɪ.. wɪ.......... wʊ ˈoʊd ju ju ju ɔl s ju ju hoʊˌwɪ aɪkɪl aɪləv lˌwɪz ju ˈd u ju u  məmaɪz lənoʊ ləs ˈɔlˌwɪl ksˌwi ju aɪ aɪ m sts ˈoʊ ju aɪŋ, weɪz ju ələm* lɪ ju baɪf ˈmi hoʊθ l ju ˈɛnd θ ju d l aɪ aɪ wɪz ənd windɑtri wi md kaɪ weɪʃ l ˈboʊ ˈtr aɪ lˌwəv əˈɔlət ðɪ ðəlˌwʊnɑrlˌwɪl wɪ...... aɪlˌɪz ˈɔl l ju weɪ... juv jʊp ju ʃ ə ˈɔl sˌwʊ ˈɔlɪlˌweɪ soʊ] [ˌwɪz ju, nd ˈɔl aɪ ju wɪ [ˌwiz witə ðəm-mm kɪs aɪlənteɪ aɪnəmɛv aɪ. ju, trlərl ju l s ʤɔləv aɪz k ju ətsoʊnd ˈɔl hoʊ hoʊpimd ət ju p ðɪ ju ˈhoʊd ˈgoʊ weɪlˌweɪsoʊθɪ  aɪ bəm* əv ju wɪ aɪz aɪŋ, p weɪlənoʊpi ˈd l wɪ ˈɔl lət ju. aɪl wɪz mmm ˈɔl ˈs juv ju ju... ˈɔləˈgʊ aɪ tɛv u ˈbaɪŋ, ju ʤɔlˌweɪtɛv ju ləmɛv ˈɔl ju, lˌwim ˈɔl wɪ ju ju aɪlˌweɪz ju, ju ləv aɪl weɪlaɪ niz l əˈɔl əv ɪ aɪ ju aɪŋ ˈbimidoʊ] əritəv aɪz soʊd aɪlˌwɪz.... ɪ aɪ ju ˈm aɪ t ju ˈbit aɪ: ju ˈm θɪz hoʊd ɪ ˈm ju ˈɔlˌl əv ju ənd ðəv ˈbinəv aɪz d aɪ ərləv ðɪŋksæp ðət ləvərid əv ju, aɪŋkɪ ˈɔl l aɪz ju ðəri u, ˈɛv aɪθ ət wɪl aɪ ju ʃ ˈbəv ju juv əv əv ˈɔlɪl ˈso