In [105]:
import numpy as np
import random
import eng_to_ipa as ipa

In [204]:
text = "testing"

In [229]:
#open text and delete whitespace
text = open("hp.txt", "r").read().replace('\n', ' ').replace('\r', '')


In [230]:
#text = ipa.convert(text)

In [231]:
text = text.split(' ')

In [232]:
l = len(text)
mat = np.zeros((70000,70000))

In [233]:
seen = {}

In [234]:
#toDo: change seen into a dictionary
seen[text[0]] = 0
count = 0
prev = 0
for i in range(1,len(text)):
    if text[i] not in seen:
        count+=1
        seen[text[i]] = count
    t = seen[text[i]]
    mat[t][prev] += 1
    prev = t

In [235]:
print(seen)

{'': 0, 'FOR': 1, 'JESSICA,': 2, 'WHO': 3, 'LOVES': 4, 'STORIES,': 5, 'ANNE,': 6, 'LOVED': 7, 'THEM': 8, 'TOO;': 9, 'AND': 10, 'DI,': 11, 'HEARD': 12, 'THIS': 13, 'ONE': 14, 'FIRST.': 15, 'CONTENTS': 16, 'The': 17, 'Boy': 18, 'Who': 19, 'Lived': 20, 'TWO': 21, 'Vanishing': 22, 'Glass': 23, 'THREE': 24, 'Letters': 25, 'from': 26, 'No': 27, 'One': 28, 'FOUR': 29, 'Keeper': 30, 'of': 31, 'the': 32, 'Keys': 33, 'FIVE': 34, 'Diagon': 35, 'Alley': 36, 'SIX': 37, 'Journey': 38, 'Platform': 39, 'Nine': 40, 'and': 41, 'Three-quarters': 42, 'SEVEN': 43, 'Sorting': 44, 'Hat': 45, 'EIGHT': 46, 'Potions': 47, 'Master': 48, 'NINE': 49, 'Midnight': 50, 'Duel': 51, 'TEN': 52, 'Halloween': 53, 'ELEVEN': 54, 'Quidditch': 55, 'TWELVE': 56, 'Mirror': 57, 'Erised': 58, 'THIRTEEN': 59, 'Nicolas': 60, 'Flamel': 61, 'FOURTEEN': 62, 'Norbert': 63, 'Norwegian': 64, 'Ridgeback': 65, 'FIFTEEN': 66, 'Forbidden': 67, 'Forest': 68, 'SIXTEEN': 69, 'Through': 70, 'Trapdoor': 71, 'SEVENTEEN': 72, 'Man': 73, 'with': 74,

In [236]:
#delete data of 1 or 0
mat= np.delete(mat,np.where(~mat.any(axis=1))[0], axis=0)
mat= np.delete(mat,np.where(~mat.any(axis=0))[0], axis=1)

In [237]:
print(mat)

[[3. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [238]:
sum_of_rows = mat.sum(axis=1)
normalized_array = mat / sum_of_rows[:, np.newaxis]

In [239]:
print(seen)
normalized_array

{'': 0, 'FOR': 1, 'JESSICA,': 2, 'WHO': 3, 'LOVES': 4, 'STORIES,': 5, 'ANNE,': 6, 'LOVED': 7, 'THEM': 8, 'TOO;': 9, 'AND': 10, 'DI,': 11, 'HEARD': 12, 'THIS': 13, 'ONE': 14, 'FIRST.': 15, 'CONTENTS': 16, 'The': 17, 'Boy': 18, 'Who': 19, 'Lived': 20, 'TWO': 21, 'Vanishing': 22, 'Glass': 23, 'THREE': 24, 'Letters': 25, 'from': 26, 'No': 27, 'One': 28, 'FOUR': 29, 'Keeper': 30, 'of': 31, 'the': 32, 'Keys': 33, 'FIVE': 34, 'Diagon': 35, 'Alley': 36, 'SIX': 37, 'Journey': 38, 'Platform': 39, 'Nine': 40, 'and': 41, 'Three-quarters': 42, 'SEVEN': 43, 'Sorting': 44, 'Hat': 45, 'EIGHT': 46, 'Potions': 47, 'Master': 48, 'NINE': 49, 'Midnight': 50, 'Duel': 51, 'TEN': 52, 'Halloween': 53, 'ELEVEN': 54, 'Quidditch': 55, 'TWELVE': 56, 'Mirror': 57, 'Erised': 58, 'THIRTEEN': 59, 'Nicolas': 60, 'Flamel': 61, 'FOURTEEN': 62, 'Norbert': 63, 'Norwegian': 64, 'Ridgeback': 65, 'FIFTEEN': 66, 'Forbidden': 67, 'Forest': 68, 'SIXTEEN': 69, 'Through': 70, 'Trapdoor': 71, 'SEVENTEEN': 72, 'Man': 73, 'with': 74,

array([[0.01020408, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.25      , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [240]:
currRow = random.randint(0, normalized_array[0].size)
currRow

2897

In [243]:
s = ""
key_list = list(seen.keys())
vals = list(seen.values())
for i in range(7000):
    n = random.randint(0, normalized_array[0].size)
    totalN = 0
    steps = 0
    randie = np.random.rand(1)[0]
    for p in normalized_array[currRow]:
        totalN += p
        if randie < totalN:
            s+= key_list[vals.index(steps)] + " "
            currRow = steps
            break
        steps+=1
        
    

In [244]:
s

'Thousand. Two with girl an’ mum yer yeh, of jars floor; the onto out answer to shoulders his whacked screamed, He’d news. bad so gets he so didn’t, he as close so anger, in there, hanging was It possession.” in cream ice chocolate of Goblet the in he’s but knuckles, his under slipped tiptoe, on Lady Fat the past half At him. at beginning the at jewels fabulous see couldn’t Quirrell said afternoon,” “Good him. around hang a had gang Dudley’s into moved had he Firenze,” is This Snitch. the on well as books, spell the missed he’d since around dive nice that made man young Or bald quite standing still not as yelled Harry ever. than harder team his inside back be will you — “Um puncture. a them conjured had he’d lead will Wood ask “Don’t ‘please.’” “Say me.” “Search teachers?” the at dragons keeping  sight. of bundle the would he .” . . . it if then, and sat Harry Astronomy. on fingers long How listen. to down quickly faded Gryffindor put her asking been had Dudley at hissing low, creaked,